image: python:3.5
variables:
    TOXENV: py35

test:
    stage: test
    before_script:
        - pip install -U pip
        - pip install tox
        - pip install setuptools
    script:
        - tox -v -- -v
    tags:
        - docker

wavedrom:
    image: node:10
    stage: test
    before_script:
        - yarn install
    script:
        - yarn run wavedrom:gpmc-burst-rd
        - yarn run wavedrom:gpmc-burst-wr
    tags:
        - docker
